// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eleoevzkclsttkhfixwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsZW9ldnprY2xzdHRraGZpeHd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTUzOTcsImV4cCI6MjA2MjI5MTM5N30._Bi6uj3JSTVlXZ9gAizvAmyxNTlU6LBRR4JGUvz9kZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);